language: objective-c
osx_image: beta-xcode6.3

before_install:
  - "sudo xcode-select --install || true"
  - "brew install carthage"
  - "cd vendor && carthage bootstrap --platform mac"
  - "cd $TRAVIS_BUILD_DIR"

install: "make"

before_script:
  # Ensure it needs to compile something
  - "touch $TRAVIS_BUILD_DIR/Roost/main.swift"
  - "echo $TRAVIS_BUILD_DIR/Roost/main.swift"


script: "bin/roost"
