language: objective-c
osx_image: beta-xcode6.3

before_install:
  - "sudo xcode-select --install || true"
  - "brew install carthage"
  - "cd vendor && carthage bootstrap --platform mac"
install: "cd $TRAVIS_BUILD_DIR && make"

before_script: "touch Roost/main.swift"
script: "bin/roost"
