language: objective-c
osx_image: xcode7.1

before_install:
  - "sudo xcode-select --install || true"
  # - 'echo "--netrc" >> ~/.curlrc'
  # - 'echo -e "machine github.com login $GITHUB_PASSWORD" > ~/.netrc'
  # - "chmod 600 ~/.netrc"
  - "brew install carthage libssh2"
  - "cd vendor && carthage bootstrap --platform mac --no-use-binaries --verbose"
  - "cd $TRAVIS_BUILD_DIR"

install: "make"

before_script: "bin/roost update"

script:
  - "bin/roost build -B"
  # Test that the clean command works
  - "bin/roost clean"
  # And that it can build after cleaning
  - "bin/roost build"
