language: objective-c
osx_image: beta-xcode6.3

before_install:
  - "sudo xcode-select --install || true"
  - "brew install carthage"
  - "cd vendor && carthage bootstrap --platform mac"
  - "cd $TRAVIS_BUILD_DIR"

install: "make"

script: "MUST_RECOMPILE=yes bin/roost"
